function init(self)
	self.target = nil
end

function update(self, dt)
	if self.target then
		local ok, cam_pos = pcall(go.get_world_position, self.target)
		if ok then
			local pos = go.get_position()
			pos.x = cam_pos.x
			pos.y = cam_pos.y
			go.set_position(pos)
		else
			self.target = nil
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("set_target") then
		self.target = message.id
	end
end