go.property("tracked", msg.url())
local track = hash("track")
local stop = hash("stop")
local upgrades = require "modules.upgrade_state"
local level_collection = require "modules.level_collection"
local eyes = hash("upgraded_eyes")

function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
	self.smoothing = 0.1
	self.tracking = false
	self.offset = vmath.vector3(0, 0, 0)
	self.width = sys.get_config_int("display.width")
	self.height = sys.get_config_int("display.height")
	-- print(msg.url())
	msg.post("#test_camera", "acquire_camera_focus")
	-- disable filter if robot_eyes are available
	if upgrades.parts.robot_eyes then
		msg.post("#filter", "disable")
	end
	self.boundaries = level_collection.boundaries[self.current_level]
	
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
	if not self.tracking then return end
	-- print(self.tracked)

	local tracked_pos = go.get_position(self.tracked)
	local current = go.get_position()

	-- smooth interpolation toward target
	local desired = tracked_pos + self.offset
	local new_pos = vmath.lerp(1 - self.smoothing, current, desired)
	new_pos.z = current.z  -- preserve camera z

	-- correct for level boundaries
	local tmp_x = self.width/2
	local tmp_y = self.height/2
	new_pos.x = math.max(new_pos.x, self.boundaries.left + tmp_x)
	new_pos.x = math.min(new_pos.x, self.boundaries.right - tmp_x)
	new_pos.y = math.max(new_pos.y, self.boundaries.bottom + tmp_y)
	new_pos.y = math.min(new_pos.y, self.boundaries.top - tmp_y)

	go.set_position(new_pos)
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
	-- print(sender)
	if message_id == track then
		self.tracking = true
		self.tracked = message.tracked
		self.boundaries = level_collection.boundaries[message.current_level]
	end

	if message_id == stop then
		self.tracking = false
	end

	if message_id == eyes then
		-- print("disable filter")
		msg.post("#filter", "disable")
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end